# monitored_tx_ids = [1, 2, 3, 4]
# transactions_ids = [3, 4, 5, 6]

# combined_set = set(monitored_tx_ids).union(transactions_ids)

# print(combined_set)

_list = [{'name': 'Rule_MM', 'title': 'Ladies Fancy Jacket - 17550', 'subtitle': False, 'product_template_id': 56062, 'product_id': 56072, 'category_number': 2406, 'marketplace_product': False, 'ref_code': False, 'variant_group_sku': False, 'variant_group_id': False, 'brand': 3, 'config_id': 4, 'is_auto_listing_enabled': True, 'is_listing_new': True, 'auto_listing_priority': '73002', 'is_use_buy_now_enabled': True, 'start_price': 103.94, 'buy_now_price': 103.94, 'buy_now_max_qty': 0, 'description': False},
 {'name': 'Rule_MM', 'title': 'Ladies Fancy Jacket - 17550', 'subtitle': False, 'product_template_id': 56062, 'product_id': 56071, 'category_number': 2406, 'marketplace_product': False, 'ref_code': False, 'variant_group_sku': False, 'variant_group_id': False, 'brand': 3, 'config_id': 4, 'is_auto_listing_enabled': True, 'is_listing_new': True, 'auto_listing_priority': '73002', 'is_use_buy_now_enabled': True, 'start_price': 103.94, 'buy_now_price': 103.94, 'buy_now_max_qty': 0, 'description': False},
 {'name': 'Rule_MM', 'title': 'Ladies Fancy Jacket - 17550', 'subtitle': False, 'product_template_id': 56062, 'product_id': 56073, 'category_number': 2406, 'marketplace_product': False, 'ref_code': False, 'variant_group_sku': False, 'variant_group_id': False, 'brand': 3, 'config_id': 4, 'is_auto_listing_enabled': True, 'is_listing_new': True, 'auto_listing_priority': '73002', 'is_use_buy_now_enabled': True, 'start_price': 103.94, 'buy_now_price': 103.94, 'buy_now_max_qty': 0, 'description': False},
 {'name': 'Rule_MM', 'title': 'Ladies Fancy Jacket - 17550', 'subtitle': False, 'product_template_id': 56062, 'product_id': 56074, 'category_number': 2406, 'marketplace_product': False, 'ref_code': False, 'variant_group_sku': False, 'variant_group_id': False, 'brand': 3, 'config_id': 4, 'is_auto_listing_enabled': True, 'is_listing_new': True, 'auto_listing_priority': '73002', 'is_use_buy_now_enabled': True, 'start_price': 103.94, 'buy_now_price': 103.94, 'buy_now_max_qty': 0, 'description': False},
 {'name': 'Rule_MM', 'title': 'Ladies Fancy Jacket - 17550', 'subtitle': False, 'product_template_id': 56062, 'product_id': 56076, 'category_number': 2406, 'marketplace_product': False, 'ref_code': False, 'variant_group_sku': False, 'variant_group_id': False, 'brand': 3, 'config_id': 4, 'is_auto_listing_enabled': True, 'is_listing_new': True, 'auto_listing_priority': '73002', 'is_use_buy_now_enabled': True, 'start_price': 103.94, 'buy_now_price': 103.94, 'buy_now_max_qty': 0, 'description': False},
 {'name': 'Rule_MM', 'title': 'Ladies Fancy Jacket - 17550', 'subtitle': False, 'product_template_id': 56062, 'product_id': 56075, 'category_number': 2406, 'marketplace_product': False, 'ref_code': False, 'variant_group_sku': False, 'variant_group_id': False, 'brand': 3, 'config_id': 4, 'is_auto_listing_enabled': True, 'is_listing_new': True, 'auto_listing_priority': '73002', 'is_use_buy_now_enabled': True, 'start_price': 103.94, 'buy_now_price': 103.94, 'buy_now_max_qty': 0, 'description': False},
 {'name': 'Rule_MM', 'title': 'Ladies Fancy Jacket - 17550', 'subtitle': False, 'product_template_id': 56062, 'product_id': 56077, 'category_number': 2406, 'marketplace_product': False, 'ref_code': False, 'variant_group_sku': False, 'variant_group_id': False, 'brand': 3, 'config_id': 4, 'is_auto_listing_enabled': True, 'is_listing_new': True, 'auto_listing_priority': '73002', 'is_use_buy_now_enabled': True, 'start_price': 103.94, 'buy_now_price': 103.94, 'buy_now_max_qty': 0, 'description': False},
 {'name': 'Rule_MM', 'title': 'Ladies Fancy Jacket - 17550', 'subtitle': False, 'product_template_id': 56062, 'product_id': 56078, 'category_number': 2406, 'marketplace_product': False, 'ref_code': False, 'variant_group_sku': False, 'variant_group_id': False, 'brand': 3, 'config_id': 4, 'is_auto_listing_enabled': True, 'is_listing_new': True, 'auto_listing_priority': '73002', 'is_use_buy_now_enabled': True, 'start_price': 103.94, 'buy_now_price': 103.94, 'buy_now_max_qty': 0, 'description': False},
 {'name': 'Rule_MM', 'title': 'Ladies Fancy Jacket - 17550', 'subtitle': False, 'product_template_id': 56062, 'product_id': 56080, 'category_number': 2406, 'marketplace_product': False, 'ref_code': False, 'variant_group_sku': False, 'variant_group_id': False, 'brand': 3, 'config_id': 4, 'is_auto_listing_enabled': True, 'is_listing_new': True, 'auto_listing_priority': '73002', 'is_use_buy_now_enabled': True, 'start_price': 103.94, 'buy_now_price': 103.94, 'buy_now_max_qty': 0, 'description': False},
 {'name': 'Rule_MM', 'title': 'Ladies Fancy Jacket - 17550', 'subtitle': False, 'product_template_id': 56062, 'product_id': 56079, 'category_number': 2406, 'marketplace_product': False, 'ref_code': False, 'variant_group_sku': False, 'variant_group_id': False, 'brand': 3, 'config_id': 4, 'is_auto_listing_enabled': True, 'is_listing_new': True, 'auto_listing_priority': '73002', 'is_use_buy_now_enabled': True, 'start_price': 103.94, 'buy_now_price': 103.94, 'buy_now_max_qty': 0, 'description': False},
 {'name': 'Rule_MM', 'title': 'Ladies Fancy Jacket - 17550', 'subtitle': False, 'product_template_id': 56062, 'product_id': 56081, 'category_number': 2406, 'marketplace_product': False, 'ref_code': False, 'variant_group_sku': False, 'variant_group_id': False, 'brand': 3, 'config_id': 4, 'is_auto_listing_enabled': True, 'is_listing_new': True, 'auto_listing_priority': '73002', 'is_use_buy_now_enabled': True, 'start_price': 103.94, 'buy_now_price': 103.94, 'buy_now_max_qty': 0, 'description': False},
 {'name': 'Rule_MM', 'title': 'Ladies Fancy Jacket - 17550', 'subtitle': False, 'product_template_id': 56062, 'product_id': 56082, 'category_number': 2406, 'marketplace_product': False, 'ref_code': False, 'variant_group_sku': False, 'variant_group_id': False, 'brand': 3, 'config_id': 4, 'is_auto_listing_enabled': True, 'is_listing_new': True, 'auto_listing_priority': '73002', 'is_use_buy_now_enabled': True, 'start_price': 103.94, 'buy_now_price': 103.94, 'buy_now_max_qty': 0, 'description': False}]

name = [i['product_id'] for i in _list]

print(name)